Exploration
===========

Project startup
---------------

Setting knitr options.

``` {r knitr_options}
require(knitr)
opts_knit$set(root.dir="..")
opts_chunk$set(fig.path="../graphs/expl-")
```

Load required libraries.
```{r load_libraries, warning=FALSE}
require(tree)
require(ggplot2)
require(ggdendro)
require(graphics)
```
Load project with ProjectTemplate.

```{r load_project, warning=FALSE}
require(ProjectTemplate)
reload.project()
```

Subsetting training and testing data
------------------------------------

```{r subset_data}
recordsForTraining <- samsungData$subject > 26
recordsForTesting  <- samsungData$subject < 7
training <- samsungData[recordsForTraining,]
test     <- samsungData[recordsForTesting,]
```

Histograms and Boxplots
-----------------------

```{r hist_box_cols_all, eval=FALSE}
numberVars <- ncol(training) - 2
digits <- nchar(as.character(numberVars))
pad <- ""; for(i in 1:digits) pad = paste(pad, "0", sep="")
pb <- txtProgressBar(style=3)
for (i in 1:numberVars){
  number = paste(pad, i, sep="");
  number = substring(number, nchar(number)-digits+1)
  filename = paste("graphs/",number,".",names(training)[i],".png", sep="")
  png(filename, width=960)
  par(mfrow = c(1, 2))
  hist(training[,i], main=paste(number,names(training)[i]),
       xlab=paste("training[,",i,"]",sep=""))
  boxplot(training[,i] ~ training$activity, main=paste(number,names(training)[i]))
  dev.off()
  setTxtProgressBar(pb, i/numberVars)
}
close(pb)
```

```{r hist_box_cols_used}
colsUsed = c("tBodyAcc.std.X"
             ,"tGravityAcc.mean.X"
             ,"tGravityAcc.energy.Z"
             ,"tGravityAcc.mean.Y"
             ,"tGravityAcc.min.Y"
             ,"fBodyAccJerk.bandsEnergy.17.32.Z"
             ,"fBodyAccMag.mad"
             ,"tBodyAcc.correlation.X.Y"
             ,"tBodyGyro.correlation.Y.Z")
pad <- "000"
digits <- 3
filename <- "graphs/colsUsed.png"
png(filename, width=1920, height=2400)
par(mfrow = c(5, 4))
for (col in colsUsed){
  i = which( colnames(training)==col )
  number = paste(pad, i, sep="")
  number = substring(number, nchar(number)-digits+1)
  hist(training[,i], main=paste(number,col),
       xlab=paste("training[,",i,"]",sep=""))
  boxplot(training[,i] ~ training$activity, main=paste(number,col))
}
dev.off()
```

Tree with all the column
------------------------

```{r tree_all_cols, fig.width=15, fig.height=10}
treeAllCols <- tree(activity ~ . -subject, data=training)
summary(treeAllCols)
plot(treeAllCols, margin=0.15, type="uniform")
text(treeAllCols, use.n=T, cex=0.8)
```

Cross validation
----------------

```{r tree_all_misc, fig.width=12, fig.height=6}
par(mfrow=c(1,2))
plot(cv.tree(treeAllCols, FUN=prune.tree, method="misclass"))
plot(cv.tree(treeAllCols))
```

```{r tree_all_pruned, fig.width=15, fig.height=10}
pruneTreeAllCols <- prune.tree(treeAllCols, best=8)
summary(pruneTreeAllCols)
plot(pruneTreeAllCols, margin=0.15, type="uniform")
text(pruneTreeAllCols, use.n=T, cex=0.8)
```

Testing
-------

```{r tree_testing}
testTreeAllCols = predict(treeAllCols, test, type="class")
table(test$activity, testTreeAllCols)
table(test$activity == testTreeAllCols)
nright = table(test$activity == testTreeAllCols)
100 * nright["TRUE"]/sum(nright)
```
